# Generated by Django 3.2.7 on 2021-10-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fechaDeNacimiento', models.DateTimeField()),
                ('fechaDeRegistro', models.DateTimeField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
