# Generated by Django 3.2.7 on 2021-10-15 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Director',
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('idPelicula', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreDePelicula', models.CharField(max_length=50)),
                ('año', models.DateTimeField()),
                ('casaProductora', models.CharField(max_length=60)),
                ('idDirector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.director')),
            ],
        ),
    ]
